// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
	"paths": {
		"/user/signup": {
		  "post": {
			"summary": "Logout",
			"tags": ["Auth"],
			"description": "",
			"operationId": "signup",
			"consumes": ["application/json"],
			"produces": ["application/json"],
			"parameters": [
			  {
				"in": "body",
				"name": "body",
				"description": "Signup",
				"required": true,
				"schema": {
				  "$ref": "#/definitions/Signup"
				}
			  }
			],
			"responses": {
			  "200": {
				"description": "OK"
			  }
			}
		  }
		},
		"/user/signin": {
		  "post": {
			"summary": "Login",
	
			"tags": ["Auth"],
	
			"description": "login",
			"operationId": "login",
			"consumes": ["application/json"],
			"produces": ["application/json"],
			"parameters": [
			  {
				"in": "body",
				"name": "body",
				"description": "Signup",
				"required": true,
				"schema": {
				  "$ref": "#/definitions/Signin"
				}
			  }
			],
			"responses": {
			  "200": {
				"description": "OK",
				"schema": {
				  "$ref": "#/definitions/ResponseUser"
				}
			  }
			}
		  }
		},
		"/user/update": {
		  "post": {
			"summary": "Update Profile",
	
			"tags": ["Auth"],
	
			"description": "userupdate",
			"operationId": "userupdate",
			"consumes": ["application/json"],
			"produces": ["application/json"],
			"parameters": [
			  {
				"in": "body",
				"name": "body",
				"description": "Signup",
				"required": true,
				"schema": {
				  "$ref": "#/definitions/Signup"
				}
			  }
			],
			"responses": {
			  "200": {
				"description": "OK",
				"schema": {
				  "$ref": "#/definitions/ResponseUser"
				}
			  }
			}
		  }
		},
		"/user/category-book/save": {
		  "post": {
			"summary": "Save Category Book",
	
			"tags": ["Category Book"],
	
			"description": "saveCategoryBook",
			"operationId": "saveCategoryBook",
			"consumes": ["application/json"],
			"produces": ["application/json"],
			"parameters": [
			  {
				"in": "body",
				"name": "body",
				"description": "Signup",
				"required": true,
				"schema": {
				  "$ref": "#/definitions/RequestSaveCategoryBook"
				}
			  }
			],
			"responses": {
			  "200": {
				"description": "OK",
				"schema": {
				  "$ref": "#/definitions/ResponseDefault"
				}
			  }
			}
		  }
		},
		"/user/category-book/update": {
		  "post": {
			"summary": "Update Category Book",
	
			"tags": ["Category Book"],
	
			"description": "updateCategoryBook",
			"operationId": "updateCategoryBook",
			"consumes": ["application/json"],
			"produces": ["application/json"],
			"parameters": [
			  {
				"in": "body",
				"name": "body",
				"description": "Signup",
				"required": true,
				"schema": {
				  "$ref": "#/definitions/RequestSaveCategoryBook"
				}
			  }
			],
			"responses": {
			  "200": {
				"description": "OK",
				"schema": {
				  "$ref": "#/definitions/ResponseDefault"
				}
			  }
			}
		  }
		}
	  },
	  "definitions": {
		"ResponseDefault": {
		  "type": "object",
		  "properties": {
			"status": {
			  "type": "boolean",
			  "default": "true"
			},
			"message": {
			  "type": "string",
			  "default": "OK"
			},
			"data": {
			  "type": "object",
			  "default": {}
			}
		  }
		},
		"ResponseUser": {
		  "type": "object",
		  "properties": {
			"status": {
			  "type": "boolean",
			  "default": "true"
			},
			"message": {
			  "type": "string",
			  "default": "OK"
			},
			"data": {
			  "$ref": "#/definitions/User"
			}
		  }
		},
		"Signup": {
		  "type": "object",
		  "properties": {
			"username": {
			  "type": "string",
			  "default": "nguyenvana"
			},
			"password": {
			  "type": "string",
			  "default": "123456"
			},
			"phone": {
			  "type": "string",
			  "default": "0123456789"
			},
			"fullname": {
			  "type": "string",
			  "default": "Nguyen Van A"
			},
			"age": {
			  "type": "integer",
			  "default": 23
			}
		  }
		},
		"Signin": {
		  "type": "object",
		  "properties": {
			"username": {
			  "type": "string",
			  "default": "nguyenvana"
			},
			"password": {
			  "type": "string",
			  "default": "123456"
			}
		  }
		},
		"User": {
		  "type": "object",
		  "properties": {
			"username": {
			  "type": "string"
			},
			"email": {
			  "type": "string"
			},
			"phone": {
			  "type": "string"
			},
			"password": {
			  "type": "string"
			},
			"full_name": {
			  "type": "string"
			},
			"age": {
			  "type": "integer",
			  "format": "int32"
			},
			"role_id": {
			  "type": "integer",
			  "format": "int32"
			},
			"created_at": {
			  "type": "string",
			  "format": "date-time"
			},
			"updated_at": {
			  "type": "string",
			  "format": "date-time"
			},
			"role": {
			  "type": "object",
			  "properties": {
				"Id": {
				  "type": "integer",
				  "format": "int32"
				},
				"role_name": {
				  "type": "string"
				},
				"role_description": {
				  "type": "string"
				}
			  }
			},
			"token": {
			  "type": "string"
			}
		  }
		},
		"RequestSaveCategoryBook": {
		  "type": "object",
		  "properties": {
			"name": {
			  "type": "string",
			  "default": "Hanh dong"
			},
			"description": {
			  "type": "string",
			  "default": "Gioi thieu ve sach"
			},
			"Images": {
			  "type": "string",
			  "default": "https://znews-photo.zingcdn.me/w480/Uploaded/mfnuy/2023_03_25/z.jpg"
			}
		  }
		}
	  }
}`

// SwaggerInfo_swagger holds exported Swagger Info so clients can modify it
var SwaggerInfo_swagger = &swag.Spec{
	Version:          "1.0",
	Host:             "petstore.swagger.io",
	BasePath:         "/v2",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server Petstore server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo_swagger.InstanceName(), SwaggerInfo_swagger)
}